# T-V-06: Dapr Secret Store Component (Local File for Development)
# From: speckit.plan - Secrets Management
# Note: In production, use Kubernetes secrets or HashiCorp Vault
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "/dapr/secrets/secrets.json"
    - name: nestedSeparator
      value: ":"
scopes:
  - backend
  - notification-service
  - recurring-service
  - audit-service
